[build]
  command = "npm run build"
  functions = "functions" # netlify dev uses this directory to scaffold and serve your functions
  publish = "dist"

[functions]
  # Directory with serverless functions, including background functions,
  # to deploy. This is relative to the base directory if one has been set, 
  # or the root directory if a base hasn’t been set.
  directory = "functions/"

# note: each of these fields are OPTIONAL
[dev]
  command = "npm run dev" # Command to start your dev server
  targetPort = 3000 # The port for your application server, framework or site generator
  port = 8888 # The port that the netlify dev will be accessible on
  publish = "dist" # The path to your static content folder
  autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address in your browser
